### ISSUE TITLE
Game crashes on turn end when deck is empty

### ISSUE THREAD

**Issue by keltoff** [Lycowolf/streaming_deckbuilder#12]
Possibly related to #11

**Comment by keltoff** [comment]
Yes it is. Pre-#11 it works ok

**Comment by Lycowolf** [comment]
In my tests with PR #11 rebased on current master, it does not crash when deck is empty. It crashes when there's no more building to destroy. Also, for some reason, in the release build the backtrace reports panic in `begin_turn`. I guess it's result of some optimization: it doesn't happen in debug build, where it correctly reports a panic in `CardContainer::break_one`

The reason for this is unchecked call to `break_one()`, that calls `self.cards.remove(0)` on empty Vec. This is a panicking error. ¨

The fix is to check if the list is empty before removing items from it. Because we might do things like this quite often, it might be a good idea to implement these functions (`break_one`, `remove `etc.) so they return `Option<Card>` as it would allow us to delay checking if list of buildings is empty after we evaluate all effects of the card. It would also make it explicit that we expect the list run dry.
